spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/X?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: 1020
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true